### ISSUE TITLE
Some unit tests fail if locales are not available

### ISSUE THREAD

**Issue by Polynomial-C** [rhinstaller/libbytesize#27]
Hi,

running the libbytesize unit tests on my system results in the following error:

```
Traceback (most recent call last):
  File "./libbytesize_unittest.py", line 346, in testHumanReadable
    locale.setlocale(locale.LC_ALL, 'cs_CZ.UTF-8')
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

because I only have the following locales on my system:

```
# locale -a
C
POSIX
de_DE
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
de_DE@euro
deutsch
en_US
en_US.iso88591
en_US.utf8
german
```

I suggest to run tests  that require specific locales only if the required locaes are really available.

**Comment by vpodzime** [comment]
Good point, I'll add the necessary checks. Thanks!
